### ISSUE TITLE
Is there really a discount on gpt-3.5-turbo for Plus users?

### ISSUE THREAD

**Issue by lox** [Cainier/gpt-tokens#24]
I was unable to substantiate this, is there a reference somewhere?

**Comment by Cainier** [comment]
I didn't buy Plus so can't verify this, but at
Received this email on June 14, 2023

<img width="566" alt="email" src="https://github.com/Cainier/gpt-tokens/assets/41921528/0ab37761-3168-4a22-a433-cffa7a2499cd">

**Comment by codergautam** [comment]
No, it's not related to ChatGPT Plus. It just means for everyone, in this case substitute the word "Plus" with "Also" and it will make more sense. I guess that's not very clear in this message (native english speaker here).

**Comment by lox** [comment]
Yeah, I thought that might have been the case!

**Comment by Cainier** [comment]
This is really an embarrassing mistake, I will remove the parameter plus in v1.1.2, and modify the billing of gpt-3.5-turbo input tokens

Thank you so much for your questions 😆
