### ISSUE TITLE
Add openai finetune model support

### ISSUE THREAD

**Issue by Undertone0809** [Cainier/gpt-tokens#31]
It seems there is not finetune model in supportModelType. A finetune example is ft:gpt-3.5-turbo-0613:company::abcdefg". I think we should support finetune model feature.

![image](https://github.com/Cainier/gpt-tokens/assets/72488598/40cb13bc-88a7-4e68-b5a1-e3d8c5a77c08)

Here is the price reference of finetune model.

![image](https://github.com/Cainier/gpt-tokens/assets/72488598/5e093d2e-a4ab-4653-a0ee-82cadd897bb4)

**Comment by Cainier** [comment]
OK，I added it in 1.2.0

- fine tune training
- fine tune model
